# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    jaminv.aclfilter.class: jaminv\ACLFilterBundle\Bridge\Doctrine\AclFilter
    jaminv.aclquery.class: jaminv\ACLFilterBundle\Bridge\Doctrine\AclQuery

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    jaminv.aclfilter:
        class: "%jaminv.aclfilter.class%"
        arguments: ['@doctrine', '@security.token_storage', '%jaminv.aclfilter.acl_walker%', '%security.role_hierarchy.roles%']

    jaminv.aclquery:
        class: "%jaminv.aclquery.class%"
        arguments: ['@doctrine']
