# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    jaminv.aclfilter.class: jaminv\ACLFilterBundle\Bridge\Doctrine\AclFilter

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    jaminv.aclfilter:
        class: "%jaminv.aclfilter.class%"
        arguments: ['@doctrine', '@security.token_storage', '%security.role_hierarchy.roles%']
